Development
Ivan-AI-hub/InnoGotchi-game-back-end pull request #1
Opened 2023-01-21 11:28 UTC by Ivan-AI-hub

2023-02-03 10:22 UTC, defoltusrnm commented
Привет. Я Сергей. На меня заделегировали ревью твоего проекта. Весь процесс у меня может занять неделю.

2023-02-07 15:04 UTC, defoltusrnm commented
[ultimate-aspnet-core-web-api-1-2nbsped_compress.pdf](https://github.com/Ivan-AI-hub/InnoGotchi-game-back-end/files/10676429/ultimate-aspnet-core-web-api-1-2nbsped_compress.pdf)
Привет. Прежде чем резолвить мои коменты ознакомся с данной литературой и сделай правки согласно гайду

2023-02-07 15:04 UTC, defoltusrnm requested changes

2023-02-07 15:04 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/AuthOptions.cs
> +    public class AuthOptions
пример с метанита?). лучше вынести appsetting и получать уже оттуда

2023-02-07 15:04 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/Program.cs
> +builder.Services.AddTransient<IMapper>(x => new Mapper(config));
маппер по-другому можно регать

2023-02-07 15:04 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/Program.cs
> +builder.Services.AddTransient<AbstractValidator<User>, UserValidator>();
флюент валидатор тоже по-другому регается

2023-02-07 15:04 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/Program.cs
> +builder.Services.AddTransient<PetFarmManager>();
почему всё транзиент? можно же скопед делать

2023-02-07 15:04 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/Program.cs
> +            // ���������, ����� �� �������������� �������� ��� ��������� ������
// óêàçûâàåò, áóäåò ëè âàëèäèðîâàòüñÿ èçäàòåëü ïðè âàëèäàöèè òîêåíà

2023-02-07 15:04 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/Controllers/BaseController.cs
> +            return int.Parse((User.FindFirst(nameof(TokenClaims.UserId))!.Value));
а что будет если UserId не инт?

2023-02-07 15:04 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/Controllers/ColaborationRequestController.cs
> +        private ColaborationRequestManager _requestManager;
этому стоит быть рид онли

2023-02-07 15:04 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/Controllers/ColaborationRequestController.cs
> +            if (!ModelState.IsValid)
если запрос уже дошел до контроллера, то чек модель стейта не нужно делать

2023-02-07 15:04 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/Controllers/ColaborationRequestController.cs
> +            var rezult = _requestManager.SendColaborationRequest(userId, recipientId);
result

2023-02-07 15:04 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Application/Managers/ColaborationRequestManager.cs
> +    public class ColaborationRequestManager
отформатируй класс

2023-02-07 15:04 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Persistence/Interfaces/IRepository.cs
> +    public interface IRepository<T> where T : class
сделай через асинхронные операции

2023-02-07 15:04 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/Middleware/BasePetViewInitializer.cs
> +                if ((manager.GetAll(filter)).Count() == 0)
!manager.GetAll(filter).Any()

2023-02-07 15:04 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/Middleware/BasePetViewInitializer.cs
> +                    for (int i = 1; i < 6; i++)
а если их вдруг станет 7?). почитай про IOption

2023-02-07 15:04 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/Middleware/BasePetViewInitializer.cs
> +                        AddImageToDb($"wwwroot/Resourses/Bodies/body{i}.svg", "petView-body", manager);
вынести бы в конфиг это

2023-02-07 15:04 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/Middleware/BasePetViewInitializer.cs
> +        private bool _isInitialize = false;
мидлварь не должна хоть как-то отвечать за инициализацию. можно вызвать из-под Program

2023-02-07 15:04 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Persistence/InnoGotchiGameContext.cs
> +        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
пустой метод

2023-02-07 15:04 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Persistence/InnoGotchiGameContext.cs
>          public InnoGotchiGameContext()
Database.EnsureCreated(); будет вызыватся при каждом запросе на апи. пользуйся миграциями

2023-02-12 19:39 UTC, Ivan-AI-hub commented on InnoGotchiGame/InnoGotchiGame.Web/Controllers/BaseController.cs
> +            return int.Parse((User.FindFirst(nameof(TokenClaims.UserId))!.Value));
Будет выброшено исключение

2023-03-11 07:43 UTC, defoltusrnm approved these changes

2023-03-11 07:43 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Application/Sorters/UserSorter.cs
> +        }
optimize if statement

2023-03-11 07:43 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Application/Validators/UserValidator.cs
> +                .Matches("(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f]
Presonally i dont undrstnd what a regex is

2023-03-11 07:43 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Domain/User.cs
> +        }
if you implementings "N-Layred" artchitecture, then check if this should be in model class

2023-03-11 07:43 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Persistence/Interfaces/IColaborationRequestRepository.cs
> +}
That's nice, but should any model have such rep interface?

2023-03-11 07:43 UTC, defoltusrnm commented on InnoGotchiGame/LoggerService/ILoggerManager.cs
> +    }
а зачем изобретать велосипед?

2023-03-11 07:43 UTC, defoltusrnm commented on InnoGotchiGame/LoggerService/LoggerManager.cs
> +}
обертка в которой не смысла

2023-03-11 07:43 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/Extensions/ServiceExtensions.cs
> +        }
название секции должно скорее быть параметром вместо нейма

2023-03-11 07:43 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/Extensions/ServiceExtensions.cs
> +        }
логгер скорее регается как транзит, иначе ты его любом синглтон объекте не получишь

2023-03-11 07:43 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/Extensions/ServiceExtensions.cs
> +        }
либо офать реф наллабл, либо хендлить все его варнинги

2023-03-11 07:43 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/Models/ErrorModel/ErrorDetails.cs
> +{
ErrorModels perhaps?

2023-03-11 07:43 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/Initializers/BasePetViewInitializer.cs
> +            }
revert if. выделить один цикл в метод и переиспользовать его.

2023-03-11 07:43 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Web/Models/Users/AddUserModel.cs
> +    }
флюент валидатор

2023-03-11 07:43 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Application/Managers/UserManager.cs
> +        }
какой хач? `var result = Convert.ToBase64String(hash);`

2023-03-11 07:43 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Persistence/Managers/RepositoryManager.cs
> +        public IUserRepository _userRepository;
`private`

2023-03-11 07:43 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Persistence/Managers/RepositoryManager.cs
> +        }
можно использовать DI

2023-03-11 07:43 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Persistence/Models/ColaborationRequest.cs
> +
ненужный `private set`

2023-03-11 07:43 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Domain/AggragatesModel/ColaborationRequestAggregate/ColaborationRequestStatus.cs
> +}
0, 1 можно опустить. по всему проекту typo в "Collaboration"

2023-03-11 14:55 UTC, Ivan-AI-hub commented on InnoGotchiGame/InnoGotchiGame.Persistence/Models/ColaborationRequest.cs
> +
private set как и приватный конструктор нужны для того чтобы EF смог заполнить данные из бд, а сами свойства оставались безопасными для использования модели в программе.

2023-03-11 15:16 UTC, Ivan-AI-hub commented on InnoGotchiGame/InnoGotchiGame.Persistence/Managers/RepositoryManager.cs
> +        }
Я правильно понимаю, что Di использовать для создания экземпляра конкретного репозитория? Просто данный фрагмент кода был реализован для того, что бы не создавались излишние репозитории, что с Di попросту не возможно, так как он создаст все еще до прихода в конструктор. Если создание 4 лишних классов каждый запрос допустимо в данной ситуации, то просто дай мне знать. Перепишу через DI.

2023-03-16 18:33 UTC, defoltusrnm commented on InnoGotchiGame/InnoGotchiGame.Persistence/Managers/RepositoryManager.cs
> +        }
ну ты все ещё можешь один раз обратиться к IServiceProvider-у, вместо new

2023-03-20 13:48 UTC, merged